### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by joostf** [olli208/minor-frisbee-app#2]
When clicking the menu button

<img width="920" alt="screen shot 2017-06-16 at 09 49 20" src="https://user-images.githubusercontent.com/1061632/27217205-34584d80-5279-11e7-8950-e4ed3ba66ed2.png">

**Comment by olli208** [comment]
I'm not using the menu atm. But also don't know where the error occurs, can't replicate the error you're seeing.

What page are you getting the error?
