### ISSUE TITLE
No inline scripts in HTML, use external js file

### ISSUE THREAD

**Issue by joostf** [olli208/minor-frisbee-app#5]
Or do you have a good reason for it?

https://github.com/olli208/minor-frisbee-app/blob/70538cde70a570d43cecf7f55504c23374797f34/static/offline/index.html#L24

**Comment by olli208** [comment]
Oops. That's a file from a different project (RTW). It's supposed to be the offline page when a user doesn't have internet. That page will then show up, but all the code is from another project, need to update it with info from this project when I use it (don't know yet).
