### ISSUE TITLE
Invalid HTML in nav section

### ISSUE THREAD

**Issue by joostf** [olli208/minor-frisbee-app#6]
A list item can only exist inside an ul or ol element.
Also it's better to put all navigation anchors inside an li element, mainly for accessibility reasons (a readspeaker then identifies each navigation item as a separate item, instead of single sentence)

https://github.com/olli208/minor-frisbee-app/blob/1cbd95f32942da079556ac4f175e8e1a3c985a8d/views/games.ejs#L13

**Comment by olli208** [comment]
Removed nav altogether for now as I didn't need it. I made it quickly a while ago but didn't know if I needed it yet
